//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextoContainer : DbContext
    {
        public ContextoContainer()
            : base("name=ContextoContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Usuarios { get; set; }
        public virtual DbSet<ProfileUser> Perfil { get; set; }
        public virtual DbSet<Formularios> Formulario { get; set; }
        public virtual DbSet<ProfileTypes> ProfileTypesSet { get; set; }
        public virtual DbSet<Formularios1> Formularios1Set { get; set; }
        public virtual DbSet<Perfiles1> Perfiles1Set { get; set; }
        public virtual DbSet<Permisos1> Permisos1Set { get; set; }
    }
}
